name: "Export Debug Deploy Godot Project"
on:
  workflow_dispatch:
    inputs:
      build-target:
        required: true
        type: choice
        description: choose the build target
        options:
          - debug
          - release
  push:
    branches: [debug,release]
jobs:
  edd:
    uses: KhraD/edd-godot/.github/workflows/base_export_debug_deploy_godot_proj.yml@main
    with:
      build-target: ${{inputs.build-target}}